### ISSUE TITLE
Hot reload janus.conf.xml

### ISSUE THREAD

**Issue by maxboehm** [freeswitch/mod_janus#5]
Hi there, just gave Freeswitch and this plugin a first try, and it both gives a great experience for a developer. Thank you!

**Is your feature request related to a problem? Please describe.**
We deploy janus horizontally, depending on the load our users generate. At the moment I start Freeswitch, I do not know yet, which servers will be relevant or even exist for using mod_janus. Use case is obvious: joining a video conference via PSTN. 

**Describe the solution you'd like**
It would be awesome if I could just reload the janus.conf.xml by api or if it would load it periodically the file. Or if I could add and remove servers through the api. I'd just need some kind of hot reload so I can add and remove servers dynamically. 

**Describe alternatives you've considered**
I tried "reload mod_janus" but since I simulated a running call, It was not possible to unload and load the module because it is locked (and I obviously don't want to stop any running calls). I also looked into the code but did not find any hints how a mechanism could look like if there is one. 

**Additional context**
Did I miss something? Is there any given mechanism in Freeswitch or in the module how I could accomplish this task? Or is this a use case nonsense from your point-of-view?

Thank you!

Kinds regards,
Max

**Comment by maxboehm** [comment]
Richard, I am planning to implement this feature. My C skills are somewhat limited, but I will get this running somehow. 

Would you merge a pull request?

I probably will expand the configuration like this:

```
<configuration name="janus.conf" description="Janus Endpoint">
  <settings>
    <param name="debug" value="false"/>
    <param name="dynamic-server" value="https://example.org/rest/get-janus-server" interval="10"/>
  </settings>
</configuration>
```

The rest api will return a JSON which corresponds to your xml 'server' tag and the module will update its' servers every n seconds according to the interval.

Are you ok with that?

**Comment by richardscreene** [comment]
Hi @maxboehm,

First of all apologies for not responding to this issue sooner - I have very little time for this project at the moment and I did not receive any notification of your issue.

I'm not sure that your solution is the best approach.  The module was not written to support large number of Janus servers and I expect you could run into all sorts of race conditions (particularly when removing servers).

Have you considered placing a load-balancer in front of the Janus servers and just configure a single Janus server in FreeSWITCH?

I apologise if my reply is too late to be of use!

**Comment by maxboehm** [comment]
Hello @richardscreene,

no worries! My answer also took some days, eh, weeks :-)

Yeah, we ran into some race conditions and we the ones we found. We'll submit a PR as soon as our time is less limited. 

Should be okay, right?

**Comment by richardscreene** [comment]
I'm not sure I'd be happy merging in such a significant PR when I haven't got time to verify the changes.I'm very happy for you the fork the repo and I can place a link to it on the README?

    On Wednesday, 12 May 2021, 13:33:43 BST, Maximilian Böhm ***@***.***> wrote:  
 
 


Hello @richardscreene,

no worries! My answer also took some days, eh, weeks :-)

Yeah, we ran into some race conditions and we the ones we found. We'll submit a PR as soon as our time is less limited.

Should be okay, right?

**Comment by maxboehm** [comment]
We are hopefully soon ready to publish it. 

Asking for compliance reasons: which license did you choose? I am not 100% sure by readme.md. Is it MPL1.1?

I would give you a short notice so that you can check the repo if you are fine with it. Hope that this is fine for you?

Kind regards,
Max

Von meinem iPhone gesendet

> Am 12.05.2021 um 14:46 schrieb richardscreene ***@***.***>:
> 
> ﻿
> I'm not sure I'd be happy merging in such a significant PR when I haven't got time to verify the changes.I'm very happy for you the fork the repo and I can place a link to it on the README?
>

**Comment by richardscreene** [comment]
Yes, it's MPL 1.1 as dictated by freeswitch.

Let me know when you've published and I put a link to it in the readme.

Be careful of memory leaks!!! (I seem to remember it was a right pain getting rid of them when terminating a server)

Good luck!

**Comment by maxboehm** [comment]
Haha, as far as I remember, we have fixed at least one in that special case :) 

Von meinem iPhone gesendet
